### ISSUE TITLE
/Fill replace and //replace doesnt work with lucky blocks

### ISSUE THREAD

**Issue by Schnitzelflo44** [alexsocha/luckyblock#81]
**Environment**
- Loader: Forge 1.8.9-11.15.1.2318-1.8.9
- Mod version: 1.8.9
- OS: Windows 10 Pro

**Describe the bug**
Worldedit and /Fill replace doesnt work.
/fill 745 75 204 753 73 211 lucky:lucky_block 0 replace minecraft:stone gives an Error (look Screnshot 1)
Worldedit says look at the console (look at Screenshot 2 and 3) 
Picture 4. shows my mods
**Screenshots**
1. ![image](https://user-images.githubusercontent.com/68322498/163454676-18ee2ce5-3cba-4bbe-b33f-0be73fa82698.png)
2. ![image](https://user-images.githubusercontent.com/68322498/163454969-3dda692f-8d72-4841-abd7-8749fadadd82.png)
3. ![image](https://user-images.githubusercontent.com/68322498/163455182-e553d6ec-fe4a-4c92-bef6-dc8b46fb7efd.png)
4. ![image](https://user-images.githubusercontent.com/68322498/163455763-da9e163c-f412-44fc-b7b5-b928113463ed.png)

**Log file**
Here is the world edit Error report
Apr 14, 2022 8:35:14 PM com.sk89q.worldedit.extension.platform.CommandManager handleCommand
SEVERE: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167)
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:220)
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
	at com.sk89q.worldedit.forge.ForgeWorldEdit.onCommandEvent(ForgeWorldEdit.java:145)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_36_ForgeWorldEdit_onCommandEvent_CommandEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:48)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:44)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Can't have a block ID above 4095 (4108 given)
	at com.sk89q.worldedit.blocks.BaseBlock.internalSetId(BaseBlock.java:145)
	at com.sk89q.worldedit.blocks.BaseBlock.<init>(BaseBlock.java:102)
	at com.sk89q.worldedit.extension.factory.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:249)
	at com.sk89q.worldedit.extension.factory.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:37)
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:57)
	at com.sk89q.worldedit.extension.factory.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:40)
	at com.sk89q.worldedit.extension.factory.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:29)
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:57)
	at com.sk89q.worldedit.internal.command.WorldEditBinding.getPattern(WorldEditBinding.java:213)
	... 33 more

**Comment by Schnitzelflo44** [comment]
World edit doesnt work because the id is over 4095 but in /fill i have still no idea

**Comment by alexsocha** [comment]
Thanks for the report, but this is most likely an issue with worldedit and not the mod
