### ISSUE TITLE
Error on server launch

### ISSUE THREAD

**Issue by KingBarker** [alexsocha/luckyblock#82]
**Environment**
- Loader: : Fabric 0.13.0
- Mod version: 1.18.2
- OS: Windows 10
- Local Server

**Describe the bug**
Crash on server start

Mod list (starts 5 lines down)

**Log file**
[22:34:26] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[22:34:26] [main/INFO]: Loading 75 mods:
	- architectury 4.2.49
	- betteradvancements 0.2.0.129
	- blossom 1.18.2-1.0.4
	- blue_endless_jankson 1.2.1 via jankson
	- cardinal-components-base 4.1.3 via trinkets
	- cardinal-components-entity 4.1.3 via trinkets
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- collective-fabric 4.26
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_fasterxml_jackson_core_jackson-annotations 2.13.1 via spoornpacks
	- com_fasterxml_jackson_core_jackson-core 2.13.1 via spoornpacks
	- com_fasterxml_jackson_core_jackson-databind 2.13.1 via spoornpacks
	- connectiblechains 2.1.1+1.18.2
	- creeperoverhaul 1.3.0
	- enchant_giver 1.1.0 via mcdw
	- endportalrecipe-fabric 2.6
	- expandedstorage 7.3.11
	- fabric 0.51.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.0+bd8a4a1860 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-furnaces 2.1.1-1.18.2
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.13.3
	- fallingtree 3.4.2
	- fiber 0.23.0-2 via collective-fabric
	- geckolib3 3.0.37
	- go-fish 1.5.0-1.18.2
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- libgui 5.3.1+1.18 via mocolors
	- libninepatch 1.1.0 via libgui
	- lucky 1.18.1-11.0
	- mcdw 4.2.5
	- minecraft 1.18.2
	- mocolors 1.4.0
	- myloot 2.1
	- ninjaphenix_container_lib 1.3.0
	- omega-config 1.2.3-1.18.1 via fabric-furnaces
	- reach-entity-attributes 2.1.1 via mcdw
	- revive 1.0.3
	- server-hats 0.9
	- spoornpacks 4.2.1-1.18.2
	- treeharvester-fabric 5.1
	- trinkets 3.3.0
	- xtraarrows 1.7.4
[22:34:26] [main/WARN]: Mod `betteradvancements` (0.2.0.129) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[22:34:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Barkyboy/Documents/MCSERVER/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[22:34:26] [main/INFO]: Compatibility level set to JAVA_16
[22:34:26] [main/INFO]: Compatibility level set to JAVA_17
[22:34:27] [main/WARN]: Reference map 'XtraArrows-refmap.json' for xtraarrows.mixins.json could not be read. If this is a development environment you can ignore this message
[22:34:27] [main/WARN]: Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
[22:34:27] [main/WARN]: @Mixin target net.minecraft.class_906 was not found go-fish.mixins.json:FishingBobberEntityRendererMixin
[22:34:27] [main/WARN]: Error loading class: net/minecraft/class_702 (java.lang.ClassNotFoundException: net/minecraft/class_702)
[22:34:27] [main/WARN]: @Mixin target net.minecraft.class_702 was not found go-fish.mixins.json:ParticleManagerMixin
[22:34:31] [main/ERROR]: No data fixer registered for marker
[22:34:33] [main/INFO]: Loading Blossom!
[22:34:33] [main/INFO]: [STDOUT]: Loading Collective (Fabric) version 4.26.
[22:34:33] [main/INFO]: Initialized entity types.
[22:34:34] [main/INFO]: [Enchant Giver] has been initiated.
[22:34:36] [main/INFO]: Hello from myLoot!
[22:34:37] [main/INFO]: Generating resources for myloot
[22:34:37] [main/WARN]: Deleting to override directory at spoornpacks/myloot
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.spoornpacks.provider.data.BlockLootTableBuilder@163ee26b for resourceType=BLOCK_LOOT_TABLE, fullName=loot_barrel
[22:34:37] [main/INFO]: Registering BlockEntityType with namespace=myloot, name=loot_barrel
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.spoornpacks.provider.assets.ModelBlockBuilder@37fec49c for resourceType=BLOCK_MODEL, fullName=loot_chest
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.spoornpacks.provider.data.BlockLootTableBuilder@1b3fadda for resourceType=BLOCK_LOOT_TABLE, fullName=loot_chest
[22:34:37] [main/INFO]: Registering BlockEntityType with namespace=myloot, name=loot_chest
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.spoornpacks.provider.assets.ModelBlockBuilder@20dd6121 for resourceType=BLOCK_MODEL, fullName=opened_loot_chest
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.spoornpacks.provider.data.BlockLootTableBuilder@7a69f4e3 for resourceType=BLOCK_LOOT_TABLE, fullName=opened_loot_chest
[22:34:37] [main/INFO]: Registering BlockEntityType with namespace=myloot, name=opened_loot_chest
[22:34:37] [main/INFO]: Registering BlockEntityType with namespace=myloot, name=loot_shulker_box
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.myloot.MyLoot$EmptyResourceProvider@811dc82 for resourceType=BLOCK_LOOT_TABLE, fullName=opened_loot_shulker_box
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.spoornpacks.provider.assets.ModelItemBuilder@ce7e450 for resourceType=ITEM_MODEL, fullName=loot_chest
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.myloot.MyLoot$EmptyResourceProvider@6b10123f for resourceType=RECIPE, fullName=loot_chest
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.spoornpacks.provider.assets.ModelItemBuilder@7d314e63 for resourceType=ITEM_MODEL, fullName=opened_loot_chest
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.myloot.MyLoot$EmptyResourceProvider@79cdfb12 for resourceType=RECIPE, fullName=opened_loot_chest
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.myloot.MyLoot$EmptyResourceProvider@2058633e for resourceType=RECIPE, fullName=loot_shulker_box
[22:34:37] [main/INFO]: Using custom ResourceProvider=org.spoorn.spoornpacks.provider.data.RecipeBuilder@37ea9b08 for resourceType=RECIPE, fullName=loot_chest_minecart
[22:34:37] [main/INFO]: Registering EntityType with namespace=myloot, name=loot_chest_minecart
[22:34:37] [main/INFO]: Done generating some resources for myloot!
[22:34:37] [main/INFO]: Hello from SpoornPacks!
[22:34:38] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'lucky'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-server-mc.1.18.2-loader.0.13.3-launcher.0.10.2.jar:0.10.2]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2975 mod.lucky.fabric.game.LuckyWorldFeature.method_23397(net.minecraft.class_3037)'
	at mod.lucky.fabric.FabricMod.registerWorldGen(FabricMod.kt:63) ~[lucky-block-fabric-1.18.1-11.0%20(1).jar:?]
	at mod.lucky.fabric.FabricMod.onInitialize(FabricMod.kt:123) ~[lucky-block-fabric-1.18.1-11.0%20(1).jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 16 more

**Comment by alexsocha** [comment]
the version you are using is not compatible with Minecraft 1.18.2, but I've fixed this in https://github.com/alexsocha/luckyblock/pull/84 and released `lucky-block-fabric@1.18.2-13.0`
