### ISSUE TITLE
Crash in 1.19.2

### ISSUE THREAD

**Issue by CDAGaming** [alexsocha/luckyblock#95]
When breaking a Lucky block spawned a Wishing Well, the following error occured causing a crash:
```
java.lang.NoSuchMethodError: 'int net.minecraft.commands.Commands.m_82117_(net.minecraft.commands.CommandSourceStack, java.lang.String)'
	at mod.lucky.forge.ForgeGameAPI.runCommand(ForgeGameAPI.kt:333) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.common.drop.action.DropActionsKt.doCommandDrop(DropActions.kt:110) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.common.drop.DropsKt$registerDefaultDrops$4.invoke(Drops.kt:228) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.common.drop.DropsKt$registerDefaultDrops$4.invoke(Drops.kt:228) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.common.drop.DropEvaluatorKt.runEvaluatedDrop(DropEvaluator.kt:134) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.common.drop.DropEvaluatorKt.runDrop(DropEvaluator.kt:141) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.common.drop.DropEvaluatorKt.runRandomDrop(DropEvaluator.kt:177) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.java.game.LuckyBlockUtilsKt.onLuckyBlockBreak(LuckyBlockUtils.kt:59) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.forge.game.LuckyBlockKt.onBreak(LuckyBlock.kt:36) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.forge.game.LuckyBlockKt.onBreak$default(LuckyBlock.kt:23) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at mod.lucky.forge.game.LuckyBlock.m_6240_(LuckyBlock.kt:73) ~[lucky-block-forge-1.19-13.2.jar%23158!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:256) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:computing_frames,xf:fml:libx:interact,re:classloading,xf:fml:libx:interact}
	at net.minecraft.server.level.ServerPlayerGameMode.m_215116_(ServerPlayerGameMode.java:218) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:computing_frames,xf:fml:libx:interact,re:classloading,xf:fml:libx:interact}
	at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:188) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:computing_frames,xf:fml:libx:interact,re:classloading,xf:fml:libx:interact}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1024) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

Currently running Forge 1.19.2 @ 43.1.2

**Comment by alexsocha** [comment]
Fixed in `lucky-block-forge@1.19.2-13.0`
